## Simple Linear Regression Practice

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#난수 발생 순서 고정
torch.manual_seed(1)

#데이터는 텐서의 형태를 가지고 있어야 되고.. 정확한 건 아직 모름
x_train = torch.FloatTensor([[1],[2],[3]])
print(x_train)
y_train = torch.FloatTensor([[2],[4],[6]])

#모델 초기화 ( W, b, optimizer) , W,b output tensor shpae이 1 이라는 거임
W = torch.zeros(1,requires_grad=True)
print(W.shape,W)
print(W.item()) #만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있다.
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W,b],lr=0.01)
print(optimizer, '\n',b)

# #가설 세우기
# hypothesis = W*x_train+b

# #비용함수 정의
# cost = torch.mean((y_train-hypothesis)**2)

# optimizer.zero_grad()
# cost.backward()
# print(x_train.grad)
# print(W.grad, b.grad) #cost는 W,b로 미분을 수행한다. 그래서 자동미분시 b,W_grad에 b,W로 미분한 값이 저장된다.
# optimizer.step()


tensor([[1.],
        [2.],
        [3.]])
torch.Size([1]) tensor([0.], requires_grad=True)
0.0
SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
) 
 tensor([0.], requires_grad=True)


In [ ]:
nb_epoch = 2000

for i in range(nb_epoch+1):
    
    hypothesis = W*x_train+b
    
    cost = torch.mean((y_train-hypothesis)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #출력문
    if i % 100 == 0 :
        print("epoch:{:4d}/{}  W:{:.3f}  b:{:.3f}  Cost:{:.6f}".format(i,nb_epoch,W.item(),b.item(),cost.item()))

In [3]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[3],[6],[9]])

#모델 초기화 : Gradient Descent
W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)
optimizer = optim.SGD([W,b],lr=0.01)


nb_epochs = 3000

for epoch in range(nb_epochs+1):
#가설 : Linear Equation
    hypothesis = W*x_train+b
#cost function : MSE
    cost = torch.mean((y_train-hypothesis)**2)
#경사하강
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
#결과 확인
    if epoch % 100 == 0:
        print("Epoch: {:4d}/{}   W: {:.3f}   b:{:.3f}   Cost:{:.6f}"
              .format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch:    0/3000   W: 0.280   b:0.120   Cost:42.000000
Epoch:  100/3000   W: 2.619   b:0.867   Cost:0.108384
Epoch:  200/3000   W: 2.700   b:0.682   Cost:0.066975
Epoch:  300/3000   W: 2.764   b:0.536   Cost:0.041386
Epoch:  400/3000   W: 2.815   b:0.421   Cost:0.025574
Epoch:  500/3000   W: 2.854   b:0.331   Cost:0.015803
Epoch:  600/3000   W: 2.886   b:0.260   Cost:0.009765
Epoch:  700/3000   W: 2.910   b:0.205   Cost:0.006034
Epoch:  800/3000   W: 2.929   b:0.161   Cost:0.003729
Epoch:  900/3000   W: 2.944   b:0.126   Cost:0.002304
Epoch: 1000/3000   W: 2.956   b:0.099   Cost:0.001424
Epoch: 1100/3000   W: 2.966   b:0.078   Cost:0.000880
Epoch: 1200/3000   W: 2.973   b:0.061   Cost:0.000544
Epoch: 1300/3000   W: 2.979   b:0.048   Cost:0.000336
Epoch: 1400/3000   W: 2.983   b:0.038   Cost:0.000208
Epoch: 1500/3000   W: 2.987   b:0.030   Cost:0.000128
Epoch: 1600/3000   W: 2.990   b:0.023   Cost:0.000079
Epoch: 1700/3000   W: 2.992   b:0.018   Cost:0.000049
Epoch: 1800/3000   W: 2.994

## Multivariable Linear regression Practice

$H(x) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3} + b$

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#데이터
x1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train = torch.FloatTensor([[75],[93],[80],[100],[70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

#model initialization (w, b, optimizer)
w1 = torch.zeros(1, requires_grad =True)
w2 = torch.zeros(1, requires_grad =True)
w3 = torch.zeros(1, requires_grad =True)
b = torch.zeros(1, requires_grad =True)

optimizer = optim.SGD([w1,w2,w3,b], lr = 1e-5)

nb_epochs = 1000
#epoch num
for epoch in range(nb_epochs+1):
    #가설
    hypothesis = x1_train*w1+x2_train*w2+x3_train*w3+b
    
    #cost function(MSE)
    cost = torch.mean((hypothesis-y_train)**2)
    
    #ccst로 H(x) 개선 
    optimizer.zero_grad() #기울기 초기화
    cost.backward() #cost 미분
    optimizer.step() #W , b  업데이트
    
    if epoch % 100  == 0 :
        print('Epoch : {:4d}/{}  w1 : {:.3f}   w2 : {:.3f}   w3 : {:.3f}   b : {:.3f}  Cost : {:.6f}'.format(
        epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))    

Epoch :    0/1000  w1 : 0.294   w2 : 0.294   w3 : 0.290   b : 0.003  Cost : 29661.800781
Epoch :  100/1000  w1 : 0.688   w2 : 0.681   w3 : 0.658   b : 0.008  Cost : 5.754573
Epoch :  200/1000  w1 : 0.697   w2 : 0.684   w3 : 0.645   b : 0.008  Cost : 5.512386
Epoch :  300/1000  w1 : 0.707   w2 : 0.686   w3 : 0.634   b : 0.008  Cost : 5.281667
Epoch :  400/1000  w1 : 0.715   w2 : 0.689   w3 : 0.622   b : 0.008  Cost : 5.061869
Epoch :  500/1000  w1 : 0.724   w2 : 0.691   w3 : 0.611   b : 0.008  Cost : 4.852424
Epoch :  600/1000  w1 : 0.733   w2 : 0.693   w3 : 0.600   b : 0.008  Cost : 4.652706
Epoch :  700/1000  w1 : 0.741   w2 : 0.695   w3 : 0.589   b : 0.009  Cost : 4.462287
Epoch :  800/1000  w1 : 0.750   w2 : 0.697   w3 : 0.579   b : 0.009  Cost : 4.280604
Epoch :  900/1000  w1 : 0.758   w2 : 0.699   w3 : 0.569   b : 0.009  Cost : 4.107294
Epoch : 1000/1000  w1 : 0.766   w2 : 0.700   w3 : 0.559   b : 0.009  Cost : 3.941866



#### 개선모델 1 : x, y가 무수히 늘어나면 안되니까,  Dot Product 이용

In [21]:
#data
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

#model
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)
optimizer = optim.SGD([W,b],lr=1e-5)

nb_epochs = 20

for epoch in range(nb_epochs+1):
    #hypothesis : linear Equation
    hypothesis = x_train.matmul(W)+b
    
    #cost function : MSE
    cost = torch.mean((hypothesis-y_train)**2)
    
    #cost 로 H(x) 최적화 : optimizer Algorithm ( Gradient Descent )
    optimizer.zero_grad() #기울기 0으로 초기화
    cost.backward() #cost 를 w, b에 대해 미분하여 기울기를 구하여  w_grad에저장 . b는 우에대지 일단 넘어가자미
    optimizer.step() # 학습률 * 기울기 곱해서 W에 빼줌
    
    print('Epoch : {:2d}/{}   Hypothesis : {}   Cost : {:.6f}'.format(
            epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))#hypothesis 그냥 출력하면 (1,5)  + grad_fn까지 같이 나옴 squeeze로 
#     (5,) 만들어 주고, detach로 grad_fn(Tensor생성한 function)분리해준다.

Epoch :  0/20   Hypothesis : tensor([0., 0., 0., 0., 0.])   Cost : 29661.800781
Epoch :  1/20   Hypothesis : tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605])   Cost : 9298.520508
Epoch :  2/20   Hypothesis : tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821])   Cost : 2915.712402
Epoch :  3/20   Hypothesis : tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097])   Cost : 915.040527
Epoch :  4/20   Hypothesis : tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307])   Cost : 287.936096
Epoch :  5/20   Hypothesis : tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891])   Cost : 91.371071
Epoch :  6/20   Hypothesis : tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812])   Cost : 29.758249
Epoch :  7/20   Hypothesis : tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805])   Cost : 10.445267
Epoch :  8/20   Hypothesis : tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440])   Cost : 4.391237
Epoch :  9/20   Hypothesis : tensor([151.9824, 182.6789, 179.992

In [25]:
#  .grad_fn 속성, 이는 Tensor 를 생성한 Function 을 참조
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
out = z.mean()

print(z, out)

#x, y는 내용물은 같지만, y는 requires_grad = False로 기울기가 기록되지 않음
print(x.requires_grad)
y = x + 1
print(y)

#x에 어떤 연산을 해서 넣는지에 따라서 바뀌어서 좀 들어간다. 먼말이지 암튼 grad_fn이랑 requires_grad랑 좀 다름.
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

#.detach() 를 호출하여 연산 기록으로부터 분리(detach)하여 이후 연산들이 추적되는 것을 방지
print(x)
print(x.detach())

print(z)
print(z.detach())

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
True
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
False
tensor(True)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]])


### 개선모델 2

In [39]:
#setting
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1) # 필수임 안하면 계속 바뀜

#data
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

#model : Linear combination
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 2000

for epoch in range(nb_epochs+1):
    #H(x) 가설, 예측 값 함수 선언
    prediction = model(x_train)
    
    #cost function nn.mocdule에 있음.
    cost = F.mse_loss(prediction,y_train)
    
    #gradient Descent 해주나..? ? 아니지 이건 따로지
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print( 'Epoch : {:4d}/{}    Cost : {:.6f}'.format(
                epoch, nb_epochs, cost.item()))

new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)

print("\n\n" ,pred_y)

Epoch :    0/2000    Cost : 31667.597656
Epoch :  100/2000    Cost : 0.225988
Epoch :  200/2000    Cost : 0.223910
Epoch :  300/2000    Cost : 0.221930
Epoch :  400/2000    Cost : 0.220059
Epoch :  500/2000    Cost : 0.218271
Epoch :  600/2000    Cost : 0.216572
Epoch :  700/2000    Cost : 0.214955
Epoch :  800/2000    Cost : 0.213415
Epoch :  900/2000    Cost : 0.211952
Epoch : 1000/2000    Cost : 0.210554
Epoch : 1100/2000    Cost : 0.209230
Epoch : 1200/2000    Cost : 0.207966
Epoch : 1300/2000    Cost : 0.206768
Epoch : 1400/2000    Cost : 0.205618
Epoch : 1500/2000    Cost : 0.204526
Epoch : 1600/2000    Cost : 0.203479
Epoch : 1700/2000    Cost : 0.202486
Epoch : 1800/2000    Cost : 0.201539
Epoch : 1900/2000    Cost : 0.200637
Epoch : 2000/2000    Cost : 0.199769


 tensor([[151.2305]], grad_fn=<AddmmBackward>)


#### 클래스로 단순 선형 회귀, 다중 선형 회귀

In [40]:
#Setting
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

#data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

#Class Declaration
class LinealRegressionModel(nn.Module): #class는 소문자임. ㄷ걍 대부분 예약어 소문자임!
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1) # data 보고 결정
    
    def forward(self,x):
        return self.linear(x) #model(x) 와 model.forward()는 똑같음.

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])    
    
class MultivariableLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
    
    def forward(self, x):
        return self.linear(x)
    

## Mini batch Training with Custom Dataset

In [45]:
#Setting
import torch 
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

torch.manual_seed(1)

#data 
x_train = torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

#model, optimizer
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

#epoch num
nb_epochs = 20

for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        
        x_train, y_train = samples
        
        #H(x)
        prediction = model(x_train)
        
        #cost function : MSE
        cost = F.mse_loss(prediction,y_train)
        
        #cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch : {:2d}/{}   Batch: {}/{}   Cost: {:.6f}'.format(epoch, nb_epochs, batch_idx, len(dataloader), cost.item()))
        

Epoch :  0/20   Batch: 0/3   Cost: 35424.417969
Epoch :  0/20   Batch: 1/3   Cost: 7990.055664
Epoch :  0/20   Batch: 2/3   Cost: 2148.731934
Epoch :  1/20   Batch: 0/3   Cost: 986.442322
Epoch :  1/20   Batch: 1/3   Cost: 465.397644
Epoch :  1/20   Batch: 2/3   Cost: 88.113068
Epoch :  2/20   Batch: 0/3   Cost: 36.668221
Epoch :  2/20   Batch: 1/3   Cost: 9.448990
Epoch :  2/20   Batch: 2/3   Cost: 3.667141
Epoch :  3/20   Batch: 0/3   Cost: 0.975254
Epoch :  3/20   Batch: 1/3   Cost: 0.906193
Epoch :  3/20   Batch: 2/3   Cost: 0.006388
Epoch :  4/20   Batch: 0/3   Cost: 0.051697
Epoch :  4/20   Batch: 1/3   Cost: 0.054978
Epoch :  4/20   Batch: 2/3   Cost: 1.199195
Epoch :  5/20   Batch: 0/3   Cost: 0.401478
Epoch :  5/20   Batch: 1/3   Cost: 0.046481
Epoch :  5/20   Batch: 2/3   Cost: 0.388473
Epoch :  6/20   Batch: 0/3   Cost: 0.538637
Epoch :  6/20   Batch: 1/3   Cost: 0.145426
Epoch :  6/20   Batch: 2/3   Cost: 0.053031
Epoch :  7/20   Batch: 0/3   Cost: 0.601826
Epoch :  7/20   

### custom dataset

In [50]:
#setting
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import Dataset

torch.manual_seed(1)

class Customdataset(Dataset):
    def __init__(self):
         self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
         self.y_data = [[152], [185], [180], [196], [142]]
        
    def __len__(self):
        return len(self.x_data)
    
    def __getitem__(self,idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x,y
    
dataset = Customdataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)


#model, optimizer
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

#epoch
nb_epochs = 20

for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataset):
        
        x_train, y_train = samples
        
        #H(x) : Linear Equation
        prediction = model(x_train)
        
        #Cost : MSE
        cost = F.mse_loss(prediction, y_train)
        
        #cost로 h(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch : {:4d}/{}   Batch: {}/{}   Cost: {:.6f}'.format(epoch, nb_epochs, batch_idx, len(dataset), cost.item()))
        

Epoch :    0/20   Batch: 0/5   Cost: 25215.304688
Epoch :    0/20   Batch: 1/5   Cost: 15332.123047
Epoch :    0/20   Batch: 2/5   Cost: 3631.480225
Epoch :    0/20   Batch: 3/5   Cost: 1153.570190
Epoch :    0/20   Batch: 4/5   Cost: 108.236061
Epoch :    1/20   Batch: 0/5   Cost: 79.761940
Epoch :    1/20   Batch: 1/5   Cost: 37.894341
Epoch :    1/20   Batch: 2/5   Cost: 5.665077
Epoch :    1/20   Batch: 3/5   Cost: 2.459033
Epoch :    1/20   Batch: 4/5   Cost: 0.417272
Epoch :    2/20   Batch: 0/5   Cost: 1.922523
Epoch :    2/20   Batch: 1/5   Cost: 0.054261
Epoch :    2/20   Batch: 2/5   Cost: 0.284908
Epoch :    2/20   Batch: 3/5   Cost: 0.003929
Epoch :    2/20   Batch: 4/5   Cost: 0.024053
Epoch :    3/20   Batch: 0/5   Cost: 1.012643
Epoch :    3/20   Batch: 1/5   Cost: 0.004206
Epoch :    3/20   Batch: 2/5   Cost: 0.463283
Epoch :    3/20   Batch: 3/5   Cost: 0.020964
Epoch :    3/20   Batch: 4/5   Cost: 0.017084
Epoch :    4/20   Batch: 0/5   Cost: 0.973626
Epoch :    4/20 

In [56]:
#훈련 후 데이터 입력
new_var = torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print(pred_y)

tensor([[151.0224]], grad_fn=<AddmmBackward>)
